### PR TITLE
Add option insiders with env-settings

### PR DESCRIPTION
**Pull request by orenc17**
This adds the option to use VSCode Insiders default configuration without setting the environment variables

### CODE REVIEW

**Comment by ammario** [comment]
Could you explain why the added complexity to the code and API is justified, over just the solution in #39 .

**Comment by orenc17** [comment]
using environment isn't user friendly in my opinion
plus i don't think the average user knows where VSCode keeps its configurations

**Comment by ammario** [comment]
Another problem is we don't want users doing `sshcode --insiders` all the time. I agree that environment variables by themselves aren't friendly to the average user, but I also [explain how to configure for VS Code Insiders on the README](https://github.com/codercom/sshcode/blob/6b49bff676286354e1bb294663ea3cde061507d2/README.md#custom-settings-directories). I think that's good enough education on how to do this.

**Comment by orenc17** [comment]
I can agree with that, i do believe that you could use 1 variable instead of 2

**Pull request closed without merging**
